default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ignis1_development
  username: lalit
  password: lalit
  host: localhost
  port: 5432

test:
  <<: *default
  database: ignis1_test
  username: lalit
  password: lalit
  host: localhost
  port: 5432

production:
  <<: *default
  database: ignis1_production
  username: ignis1
  password: <%= ENV['IGNIS1_DATABASE_PASSWORD'] %>
